pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

	dependencies {
	        implementation 'com.github.Supersoft-Corporation:SL-SDK-Android:Tag'
	}

rootProject.name = "SL-SDK-Android"
include ':softlink-android-sdk'
